$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: true 
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code 
  - name 
  - programs
  - dbgap_accession_number

uniqueKeys:
  - [ id ]
  - [ code ]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

properties:
  type:
    type: string
  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project." # TOREVIEW
  name:
    type: string
    description: "Display name/brief description for the project." # TOREVIEW
  code:
    type: string
    description: "Unique identifier for the project."
  date_collected:
    description: "The date or date range in which the project data was collected."
    type: string
  availability_type:
    description: "Is the project open or restricted?"
    enum:
      - Open
      - Restricted
  availability_mechanism:
    description: "Mechanism by which the project will be made avilable."
    type: string
  support_source:
    description: "The name of source providing support/grant resources."
    type: string
  support_id:
    description: "The ID of the source providing support/grant resources."
    type: string
  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      Indicates that the project is logically part of the indicated project.
  state:
    description: |
      The possible states a project can be in.  All but `open` are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing


        # closed: The closed state is introduced to replace the
        #         ``legacy`` state and means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

        # DEPRECATED(2016-03-01): synonymous with closed. included for
        #                         backwards compatibility
        - legacy

  released:
    description: |
      To release a project is to tell the GDC to include all submitted
      entities in the next GDC index.
    default: false
    type: boolean

  releasable:
    description: |
      A project can only be released by the user when `releasable` is true.
    default: false
    type: boolean

  intended_release_date:
    description: Tracks a Project's intended release date.
    type: string
    format: date-time
  dbgap_accession_number:
    type: string
    description: "The dbgap accession number provided for the project. (CMG)"
    
  dbgap_phs:
    description: >-
      The dbGaP phs accession.
    type: string
    
  dbgap_version:
    description: >-
      The dbGaP version (example, v1).
    type: string
    
  dbgap_participant_set:
    description: >-
      The dbGaP participant set (example, p1).
    type: string
    
  dbgap_consent:
    description: >-
      The dbGaP consent number (example, c1).
    type: string
    
  dbgap_consent_text:
    description: >-
      The dbGaP consent text (example, HMB-IRB).
    type: string    
    
  authz:
    description: >-
      The authz string (example, ["/programs/Program.name/projects/Project.code"] ).
    type: array
    items:
      type: string
        
  short_name:
    description: >-
      The shorthand name for the project.
    type: string
        
  full_name:
    description: >-
      The full name for the project.
    type: string
        
  study_description:
    description: >-
      The description for the project.
    type: string    

  study_registration:
    description: >-
      External source from which the identifier included in study_id originates
    type: string
    
  study_id:
    description: >-
      Unique identifier that can be used to retrieve more information for a study
    type: string
